import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.1/build/three.module.js';
import { UI } from './UI.js'; import { TouchInput } from './Input.js';import { Player } from './Player.js';import { WeaponSystem } from './WeaponSystem.js';import { BotAI } from './BotAI.js';
class AudioEngine {constructor(){this.ctx=null;}init(){this.ctx??=new(window.AudioContext||window.webkitAudioContext)();this.ctx.resume();}tone(freq=.1,vol=.08){if(!this.ctx)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),t=this.ctx.currentTime;o.connect(g).connect(this.ctx.destination);o.frequency.value=freq;g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.001,t+vol);o.start(t);o.stop(t+vol);}shot(t){this.tone(t==='awp'?65:120,t==='awp'?.36:.12)}click(){this.tone(540,.04)}}
class Game {constructor(){this.ui=new UI();this.audio=new AudioEngine();this.ui.onPlay=()=>this.start();this.ui.onExit=()=>this.exit();this.ui.onQuality=q=>this.quality=q;this.quality='medium';this.running=false;this.bindUI();}
 bindUI(){const actions={fire:['fire','left-fire'],jump:['jump'],crouch:['crouch'],reload:['reload'],inspect:['inspect'],zoom:['zoom']};Object.entries(actions).forEach(([action,ids])=>ids.forEach(id=>this.ui.el(id).dataset.action=action));document.querySelectorAll('#slots button').forEach(b=>b.addEventListener('click',()=>this.weapon?.set(b.dataset.weapon)||this.ui.toast(b.dataset.weapon==='grenade'?'Граната скоро будет доступна':'Выбрано')));}
 init(){if(this.scene)return;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x91a7ae);this.scene.fog=new THREE.Fog(0x91a7ae,18,58);this.camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.1,100);this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05;this.ui.el('game').append(this.renderer.domElement);this.scene.add(new THREE.HemisphereLight(0xfff1d2,0x476068,1.6));const sun=new THREE.DirectionalLight(0xffe2b0,2.7);sun.position.set(-12,22,10);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);this.scene.add(sun);this.player=new Player(this.camera);this.buildMap();this.weapon=new WeaponSystem(this.camera,this.scene,this.ui.el('skin').value,this.audio);this.input=new TouchInput({moveZone:this.ui.el('move-zone'),lookZone:this.ui.el('look-zone'),stick:this.ui.el('joystick'),onAction:(a,on)=>this.action(a,on)});addEventListener('resize',()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight)});this.last=performance.now();requestAnimationFrame(t=>this.frame(t));}
 buildMap(){this.walls=[];const tex=(color,rough=.8)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:rough<.5?.45:0});const ground=new THREE.Mesh(new THREE.PlaneGeometry(100,100),tex(0xa77e58));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;this.scene.add(ground);const add=(x,z,w,h,d,c=0xb98051)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),tex(c));m.position.set(x,h/2,z);m.castShadow=m.receiveShadow=true;m.frustumCulled=true;this.scene.add(m);this.walls.push(m);};add(0,-31,64,7,2);add(0,31,64,7,2);add(-31,0,2,7,64);add(31,0,2,7,64);[-14,0,14].forEach((x,i)=>{add(x,-7,5,3.5,5,i===1?0x5f706d:0xb67943);add(-x,11,4,4,7,0x92734e)});for(let i=0;i<90;i++){const p=new THREE.Points(new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute([(Math.random()-.5)*54,Math.random()*7,(Math.random()-.5)*54],3)),new THREE.PointsMaterial({color:0xffe2a3,size:.035,transparent:true,opacity:.5}));this.scene.add(p);}}
 blocked(pos){return this.walls.some(w=>Math.abs(pos.x-w.position.x)<w.geometry.parameters.width/2+.35&&Math.abs(pos.z-w.position.z)<w.geometry.parameters.depth/2+.35)}
 spawn(){this.bots?.forEach(b=>this.scene.remove(b.group));this.bots=[];for(let i=0;i<5;i++){let p;do p=new THREE.Vector3((Math.random()-.5)*43,0,(Math.random()-.5)*43);while(this.blocked(p)||p.distanceTo(this.camera.position)<10);this.bots.push(new BotAI(this.scene,p));}this.kills=0;this.ui.score(0);}
 async start(){this.audio.init();await this.ui.loading();this.init();this.player.camera.position.set(0,1.7,20);this.spawn();this.running=true;this.ui.hud(true);this.ui.toast('ДВОЙНОЙ ОГОНЬ ВКЛЮЧЁН');}
 exit(){this.running=false;this.ui.hud(false);this.ui.el('menu').classList.remove('hidden');}
 action(a,on){if(!this.running)return;if(a==='fire')this.firing=on;if(!on)return;if(a==='jump')this.player.jump();if(a==='crouch')this.player.toggleCrouch();if(a==='reload')this.weapon.reload();if(a==='inspect')this.weapon.inspect();if(a==='zoom'&&this.weapon.toggleZoom()){this.camera.fov=this.weapon.zoomed?35:72;this.camera.updateProjectionMatrix();}}
 fire(){const result=this.weapon.shoot(this.bots);if(!result)return;if(result.hit){const bot=this.bots.find(b=>b.group===result.hit.object.parent);if(bot){this.ui.hit();if(bot.damage(result.damage*(result.head?2:1))){this.scene.remove(bot.group);this.bots.splice(this.bots.indexOf(bot),1);this.kills++;this.ui.score(this.kills);this.ui.kill();navigator.vibrate?.([35,35,35]);setTimeout(()=>this.bots.push(new BotAI(this.scene,new THREE.Vector3((Math.random()-.5)*40,0,(Math.random()-.5)*40))),1800);}}}}
 frame(now){requestAnimationFrame(t=>this.frame(t));const dt=Math.min(.033,(now-this.last)/1000);this.last=now;if(!this.running)return;const moving=this.player.update(dt,this.input,p=>this.blocked(p));this.weapon.update(dt,moving,{x:this.input.look.x,y:this.input.look.y});if(this.firing)this.fire();this.ui.ammo(this.weapon.state);for(const b of this.bots)if(b.update(dt,this.camera,!this.blocked(b.group.position))){this.ui.damage();navigator.vibrate?.(80);this.audio.tone(80,.1)}this.renderer.shadowMap.enabled=this.quality!=='low';this.renderer.render(this.scene,this.camera);}}
new Game();
