import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.1/build/three.module.js';
const SPECS={knife:{name:'НОЖ',mag:0,reserve:0,delay:.45,damage:55},glock:{name:'GLOCK',mag:20,reserve:120,delay:.18,damage:25},ak:{name:'AK-47',mag:30,reserve:90,delay:.095,damage:34},awp:{name:'AWP',mag:5,reserve:20,delay:1.1,damage:120}};
export class WeaponSystem {
  constructor(camera, scene, skin, audio) { this.camera=camera;this.scene=scene;this.skin=skin;this.audio=audio;this.group=new THREE.Group();camera.add(this.group);this.type='ak';this.ammo={};Object.entries(SPECS).forEach(([k,v])=>this.ammo[k]={mag:v.mag,reserve:v.reserve});this.cooldown=0;this.recoil=0;this.inspectTime=0;this.zoomed=false;this.set('ak'); }
  set(type){if(!SPECS[type]||type==='grenade')return;this.type=type;this.group.clear();const g=new THREE.Group(), metal=new THREE.MeshStandardMaterial({color:0x15191c,metalness:.85,roughness:.24}), paint=new THREE.MeshPhysicalMaterial({color:this.skin==='redline'?0x9c1818:this.skin==='asimov'?0xe6e0ca:0x394048,metalness:.55,roughness:.3,clearcoat:.25}); const add=(geo,mat,x,y,z,rx=0)=>{const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);m.rotation.x=rx;g.add(m);};
    if(type==='knife'){add(new THREE.BoxGeometry(.055,.08,.65),metal,.08,-.07,-.42);add(new THREE.BoxGeometry(.1,.11,.2),paint,.08,-.1,.0)}else if(type==='awp'){add(new THREE.BoxGeometry(.12,.14,.95),paint,.18,-.14,-.55);add(new THREE.CylinderGeometry(.025,.025,.75),metal,.18,-.13,-1.22,Math.PI/2);add(new THREE.CylinderGeometry(.055,.055,.42),metal,.18,.02,-.55,Math.PI/2)}else{const len=type==='ak'?.75:.38;add(new THREE.BoxGeometry(.1,.15,len),paint,.18,-.15,-.43);add(new THREE.CylinderGeometry(.025,.025,type==='ak'?.43:.2),metal,.18,-.13,-.9,Math.PI/2);if(type==='ak')add(new THREE.BoxGeometry(.1,.28,.14),metal,.18,-.33,-.3,.25)}
    g.position.set(0,0,0);this.group.add(g);this.model=g;this.base=g.position.clone(); }
  shoot(bots){const spec=SPECS[this.type], state=this.ammo[this.type];if(this.cooldown>0||(!state.mag&&this.type!=='knife'))return false;if(this.type!=='knife')state.mag--;this.cooldown=spec.delay;this.recoil+=this.type==='awp'?.16:.045;this.audio.shot(this.type);if(navigator.vibrate)navigator.vibrate(15);const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(),this.camera);const hits=ray.intersectObjects(bots.map(b=>b.group),true);return {hit:hits[0],damage:spec.damage,head:hits[0]?.object.userData.head};}
  reload(){const s=this.ammo[this.type],spec=SPECS[this.type];if(!s||!s.reserve||s.mag===spec.mag||this.cooldown>0)return;const need=spec.mag-s.mag,take=Math.min(need,s.reserve);this.cooldown=1.25;setTimeout(()=>{s.mag+=take;s.reserve-=take;this.audio.click();},1100);}
  update(dt,moving,look){this.cooldown=Math.max(0,this.cooldown-dt);this.recoil=THREE.MathUtils.damp(this.recoil,0,12,dt);this.inspectTime=Math.max(0,this.inspectTime-dt);if(!this.model)return;const bob=moving?Math.sin(performance.now()*.012)*.018:0;this.model.position.lerp(new THREE.Vector3(this.base.x+look.x*.00025,this.base.y+bob,this.base.z+this.recoil),.2);this.model.rotation.z=this.inspectTime?Math.sin(performance.now()*.005)*.65:0;}
  inspect(){this.inspectTime=1.5;this.audio.click();} toggleZoom(){if(this.type!=='awp')return false;this.zoomed=!this.zoomed;return this.zoomed;} get state(){return this.ammo[this.type];} }
